apiVersion: anubis.techaro.dev/v1alpha1
kind: AnubisProxy
metadata:
  name: anubis-demo
  namespace: anubis-demo
spec:
  mode: forwardAuth

  target:
    service:
      name: nginx
      port: 80

  anubis:
    port: 8080
    keys:
      existingSecret: anubis-key
    existingConfigMap: anubis-policy
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

  forwardAuth:
    traefik:
      host: anubis-demo.example.com
      entryPoints:
        - websecure
      tlsSecret: anubis-demo-tls
      bypassRoute:
        enabled: true
      ingressRoute:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
      middleware:
        annotations:
          example.com/annotation: test
        spec:
          maxResponseBodySize: 8192
